2020-03-29 14:49:16,431 INFO [root] [__init__.py(<module>:11)] - TEst2-------------------
2020-03-29 14:49:16,971 INFO [root] [test_login_params.py(test01_login:50)] - 登录的结果为：{'success': True, 'code': 10000, 'message': '操作成功！', 'data': '37cd16ca-e400-4bc2-a471-040060c1a9b2'}
2020-03-29 14:49:17,051 INFO [root] [test_login_params.py(test01_login:50)] - 登录的结果为：{'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-03-29 14:49:17,125 INFO [root] [test_login_params.py(test01_login:50)] - 登录的结果为：{'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-03-29 14:49:17,222 INFO [root] [test_login_params.py(test01_login:50)] - 登录的结果为：{'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-03-29 14:49:17,310 INFO [root] [test_login_params.py(test01_login:50)] - 登录的结果为：{'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-03-29 14:49:17,389 INFO [root] [test_login_params.py(test01_login:50)] - 登录的结果为：{'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-03-29 14:49:17,482 INFO [root] [test_login_params.py(test01_login:50)] - 登录的结果为：{'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-03-29 14:49:17,574 INFO [root] [test_login_params.py(test01_login:50)] - 登录的结果为：{'success': True, 'code': 10000, 'message': '操作成功！', 'data': 'b9fcf1fb-9d75-46cb-a942-ff3f3e348c5d'}
2020-03-29 14:49:17,661 INFO [root] [test_login_params.py(test01_login:50)] - 登录的结果为：{'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-03-29 14:49:17,894 INFO [root] [test_login_params.py(test01_login:50)] - 登录的结果为：{'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-03-29 14:49:18,159 INFO [root] [test_login_params.py(test01_login:50)] - 登录的结果为：{'success': False, 'code': 99999, 'message': '抱歉，系统繁忙，请稍后重试！', 'data': None}
2020-03-29 14:49:18,240 INFO [root] [test_login_params.py(test01_login:50)] - 登录的结果为：{'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-03-29 14:49:31,194 INFO [root] [__init__.py(<module>:11)] - TEst2-------------------
